# Generated by Django 4.1.7 on 2023-06-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.CharField(default='test', max_length=40),
            preserve_default=False,
        ),
    ]
